name: checkstyle
on:
  pull_request:
jobs:
  java-checkstyle:
    name: "java checkstyle new"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Maven Action
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.4
      - name: Run java checkstyle
        run:
          cd fe && mvn clean checkstyle:test


