name: checkstyle
on:
  pull_request:
  push:
jobs:
  java-checkstyle:
    name: "java checkstyle"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.5.1
        id: java_checkstyle
        with:
          checkstyle_config: checkstyle.xml
          checkstyle_version: 9.3
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: 'testtool'





